"""Reference registry and deterministic level diagrams. Never generates concept art."""
import json, pathlib
ROOT=pathlib.Path(__file__).resolve().parents[1]
BASE=ROOT/'Docs/Art/Bellheart'
entries=[]
def add(folder,subject,view,description,assets,details='',status='planned'):
    stem=f'CW_BH_{subject}_{view}_V001' if view else f'CW_BH_{subject}_V001'
    entries.append(dict(id='BH-'+subject.replace('_','-')+('-'+view.replace('_','-') if view else ''),name=description,category=folder.split('_',1)[1],file=f'{folder}/{stem}.png',status=status,description=description,purpose=details or description,used_by=assets.split(','),views=view,version=1,provenance='pending',review_notes=[],prompt=details))
add('01_Island','ISLAND','MASTER_AERIAL','Entire Bellheart Isle master','L_Bellheart','Entire island elevated south-to-north view; exact canonical spatial plan from style bible.')
for view,desc in [('TOPDOWN','Measured north-up level map'),('GAMEPLAY_FLOW','Traversal and quest routing'),('ELEVATION','Terrain and landmark elevations')]:add('01_Island','ISLAND',view,desc,'L_Bellheart',desc)
add('02_BellTower','BELLTOWER','MASTER','Bell Tower master','SM_BH_BellTower,BP_BH_BellMechanism','Hero south-east view. Four pale limestone corner piers, 8x7m footprint, 32m tall, pointed front arch, single bronze bell at top, timber service deck, east exterior stair, broken west parapet, split-bell teal banner. Human scale figure 1.8m.')
add('02_BellTower','BELLTOWER','TURNAROUND','Bell Tower orthographic elevations','SM_BH_BellTower','Four labeled FRONT / EAST SIDE / REAR / WEST SIDE views of exactly the reference tower, aligned heights and same openings. Neutral cream background. No perspective invention.')
add('02_BellTower','BELLTOWER','INTERIOR','Bell Tower accessible service deck','SM_BH_BellTower,BP_BH_BellMechanism','Interior cutaway revealing stair arrival, timber maintenance deck, bronze bell suspension, reachable missing clapper socket and safety rail. Same tower.')
add('02_BellTower','BELLTOWER','BELL_MECHANISM','Bellheart installation mechanism','SM_BH_Bellheart,BP_BH_BellMechanism','Mechanical detail sheet, assembled and exploded views: bronze bell yoke, pivot, pendant socket, removable bronze clapper with teal inlay and split-bell motif. Installation lever accessible from timber service deck. Show 70cm clapper.')
add('04_FishingShop','FISHSHOP','MASTER','The Cloud Catch master','SM_BH_FishingShop,BP_BH_FishingShop','9x7m building, 6.2m high single swept teal-shingle gable, pale stone plinth, honey oak frame. West stone chimney, south covered counter with rope-wrapped posts, east door, north stockroom window. Oval hanging fish sign THE CLOUD CATCH. Mira not necessary in architectural master.')
add('04_FishingShop','FISHSHOP','EXTERIOR_TURNAROUND','The Cloud Catch exterior elevations','SM_BH_FishingShop','Same shop orthographic FRONT / EAST SIDE / REAR / WEST SIDE. Align ridge, counter, chimney and door positions. No redesigned roof.')
add('04_FishingShop','FISHSHOP','INTERIOR','The Cloud Catch interior','SM_BH_FishingShop,BP_BH_FishingShop','Same shop interior viewed through south counter, rods, bait jars, hook drawers, nets, rope, buckets, brass weighing scale, lanterns, shelves, fish trophy, teal cloth. Keep central work aisle readable. West chimney, east door.')
add('04_FishingShop','FISHSHOP','COUNTER_DISPLAY','Mira counter and physical merchandise','BP_BH_ShopDisplay','Two-panel counter closeup and item-display elevation, same shop. Rod stand left, bait jars center, hook/line spools right, teal mats and simple bronze price tags. No giant menu.')
add('05_Blacksmith','BLACKSMITH','MASTER','Bram’s Forge master','SM_BH_Blacksmith,BP_BH_Blacksmith','11x8m,6.8m ridge, asymmetric swept teal gable, pale stone west forge/chimney, oak south sales counter, east hand-cranked grindstone, rear anvil bay, hanging original split-bell banner. Broad welcoming silhouette, detailed joinery, same warm crafted quality as supplied forge.')
add('05_Blacksmith','BLACKSMITH','EXTERIOR_TURNAROUND','Bram’s Forge front side rear','SM_BH_Blacksmith','Aligned FRONT / EAST / REAR views of same building. Preserve west chimney, east grindstone, south counter and asymmetric teal roof.')
add('05_Blacksmith','BLACKSMITH','INTERIOR_COUNTER_STATION','Bram’s Forge interior and sharpening details','SM_BH_Blacksmith,BP_BH_Sharpening','Three useful panels: spacious interior with west forge and rear tool wall; knife on teal counter mat; east grindstone crank/axle/support close-up. Same building; warm daylight and small lantern pools. No character redesign.')
for folder,sub,name,desc in [('06_ElderHouse','ELDERHOUSE','Bellkeeper’s House','8x7m,6m ridge, teal gable, east limestone chimney, south arched door, west round study window. Old maps, books, bronze bells, fireplace, quest table.'),('07_Workshop','WORKSHOP','Tinker’s Workshop','12x9m,7m ridge, teal main gable with sawtooth annex, wide south skiff repair doors, east external pulley crane, west loft window. Skiff hull jig, rope hoists, repair bench and parts.')]:
    add(folder,sub,'MASTER',name+' exterior master','SM_BH_'+sub,desc+' South-east exterior three-quarter with small side elevation inset.')
    add(folder,sub,'INTERIOR',name+' interior','SM_BH_'+sub,desc+' Interior cutaway matching the exterior, continuous doors and windows, clear 1.2m work aisle.')
add('08_Dock','DOCK','MASTER','Bellheart Dock master','SM_BH_Dock,BP_BH_Skiff','Lowest south tip, 4m wide oak pier, east skiff berth, rope rails and posts, cargo, lanterns, two small fishing platforms. Clear north arrival path rises to pond and distant tower. Aerial close view.')
add('08_Dock','DOCK','ARRIVAL_AND_RETURN','Dock arrival and reverse sightlines','L_Bellheart,SM_BH_Dock','Two matched eye-level views: looking north from dock up arrival path to pond/tower; looking south back from island to dock and eastern skiff berth. Preserve layout.')
add('09_GiantTree','GIANTTREE','MASTER','Lantern tree master','SM_BH_GiantTree','17m tall,20m broad crown,2.8m trunk with three spreading boughs, dense layered broad leaf masses, hanging lanterns, exposed roots joined to rocks, flowers and sitting nook. Located west of pond. Scale person.')
add('09_GiantTree','GIANTTREE','BASE_AND_SILHOUETTE','Tree roots and modeling silhouette','SM_BH_GiantTree','Same tree: base closeup roots and bench/hidden collectible recess; front silhouette; side silhouette. Three main boughs and crown widths preserved. Useful modeling sheet.')
add('10_Pond','POND','MASTER','Central pond and arena master','BP_BH_FishingZone,L_Bellheart','46x34m irregular turquoise basin, village north, tree northwest, open22x18m flat eastern arena, southern tutorial bank, west waterfall outlet. Three-quarter from southeast, full shoreline readable, fish silhouettes in water, access gaps in fence.')
add('10_Pond','POND','NORTH_SOUTH_BANKS','Pond access bank views','BP_BH_FishingZone','Two matched bank views: from south fishing bank north toward village/tower; from north bank south toward arrival bridge. Rounded pale shoreline rocks, clear standing ledges, same pond.')
add('10_Pond','POND','WATERFALL_ARENA','Waterfall outlet and Bellcrab emergence bay','BP_BH_FishingZone,BP_BH_BellcrabArena','Two panels: west outlet waterfall from6m water surface to-18m airborne cascade; eastern 22x18m arena, clear emergence ramp, two broad retreat routes, sparse edge vegetation. No giant boulders blocking combat.')
characters=[('ORIN','Elder Orin','174cm elderly lean man, long silver brows, short forked beard, warm thoughtful eyes, teal long waistcoat over cream shirt, umber trousers and boots, bronze bell pendant, rolled chart.'),('MIRA','Mira','168cm adult woman, warm brown skin, curly auburn hair in short practical braid, alert friendly eyes, teal bandana, cream rolled sleeves, fitted teal vest, ochre sash, brown boots, bait pouch and net basket.'),('BRAM','Bram','190cm broad adult craftsman, warm tan skin, thick swept dark hair, full square dark beard, friendly eyes and nose, cream rolled sleeves, dark brown leather apron with split-bell patch, bronze buckles, strong hands.'),('TAVI','Tavi','172cm young adult villager, slim build, olive skin, short wavy black hair, freckles, cheerful face, mustard short jacket, teal scarf, cream undershirt, patched brown trousers, satchel and small brass telescope.')]
for sub,name,desc in characters:add('11_NPCs','NPC_'+sub,'CHARACTER_SHEET',name+' definitive character sheet','SK_BH_'+name.replace(' ','')+',BP_BH_NPC_'+sub,desc+' All adults 6.5-head proportions, believable joints, expressive but not anime. FRONT / THREE QUARTER / SIDE / REAR / FACE CLOSEUP, same person across views. Cream studio background, clothing breakdown and palette swatches. No weapons unless specified.')
add('12_Fish','FISH','STYLE_MASTER','Fish family design language','DA_BH_FishSpecies','Studio fish family sheet. Six distinct species: Cloudfin silver-blue round body with broad cloudlike fins; Pebble Carp moss olive deep body stone-like scale plates; Lantern Minnow tiny teal amber luminous throat; Silver Snapper sleek silver angular jaw and red-gold fins; Stonejaw broad slate head ochre dorsal; Golden Cloudfin exactly same body as Cloudfin with golden colors. Readable natural eyes, selective broad scales, stylized not realistic. Side silhouettes and head/fin/scale treatment.')
fish=[('CLOUDFIN','Cloudfin','35cm, silver blue plump body, broad pale cloud-shaped fins, soft blunt snout'),('PEBBLECARP','Pebble Carp','45cm, deep olive body, rounded stone-like scale plates, short rounded ochre fins, small barbels'),('LANTERNMINNOW','Lantern Minnow','18cm, slender teal body, glowing amber throat pouch, translucent rounded fins'),('SILVERSNAPPER','Silver Snapper','55cm, sleek silver torpedo body, squared jaw, pointed red-gold fins'),('STONEJAW','Stonejaw','75cm, broad slate blue armored head and thick ochre dorsal fin, heavy body'),('GOLDENCLOUDFIN','Golden Cloudfin','35cm, identical mesh silhouette and fins to Cloudfin, warm gold body and cream-gold cloud fins; rare color variant')]
for sub,name,desc in fish:add('12_Fish','FISH_'+sub,'',name+' species sheet','SM_BH_'+sub+',DA_BH_'+sub,desc+'. Same stylization as fish master; SIDE / FRONT / TOP / THREE QUARTER views aligned, scale ruler and palette, cream studio background. Consistent same fish across all views.')
add('13_Bellcrab','BELLCRAB','MASTER','Bellcrab boss master','SK_BH_Bellcrab,BP_BH_Bellcrab','Original fantasy crab 4.8m wide claws extended,2.2m high,3.5m deep. Six walking legs plus two large blunt claws, chunky domed stone-blue shell with three bronze fragments, warm ochre joints. Teal inset weakpoint under central hinged bronze shell plate, split-bell motif. Non-grotesque readable friendly-dangerous silhouette. Three-quarter on cream backdrop, 1.8m human scale.')
add('13_Bellcrab','BELLCRAB','TURNAROUND','Bellcrab aligned turnaround','SK_BH_Bellcrab','Same boss FRONT / SIDE / REAR / TOP, exactly six walking legs plus two claws, same three bronze fragments and weakpoint plate. Neutral backdrop with scale markers.')
add('13_Bellcrab','BELLCRAB','ATTACK_WEAKPOINT_SCALE','Boss telegraphs and weakpoint','ABP_BH_Bellcrab,BP_BH_Bellcrab','Same boss multi-panel animation reference: raised claw slam telegraph, forward charge crouch, double swipe broad arc, opened central bronze plate exposing teal weakpoint, 1.8m human beside4.8m boss. Arrows only indicate attacks, not extra limbs.')
for sub,title,assets,desc in [('RODS','Old Rod and Basic Rod','SM_BH_OldRod,SM_BH_BasicRod','Old Rod 190cm tapered weathered oak simple iron reel, cord wraps; Basic Rod 210cm straight honey oak, brass reel, reinforced teal wraps. Side, reel detail and line-guide detail of both.'),('KNIFE_LINE_HOOK','Iron Knife, Reinforced Line and Basic Hook','SM_BH_IronKnife,SM_BH_ReinforcedLine,SM_BH_BasicHook','28cm iron working knife, broad single-edge blade, leather cord grip, bronze ring pommel;12cm line spool dark iron with cord;3cm bronze fishing hook. Orthographic and three-quarter views each, measured scale, no modern plastic.'),('BAIT_BASKET','Bellcrab Bait and Fish Basket','SM_BH_BellcrabBait,SM_BH_FishBasket','15cm bronze chime-lure enclosed in braided teal bait bundle with hook eye;55x35x40cm woven willow fish basket, leather shoulder strap, hinged lid, broad opening. Multiple angles and materials.'),('BELLHEART','Bellheart quest object','SM_BH_Bellheart','70cm tall bronze bell clapper, rounded weighted lower bulb, narrow neck, keyed top pivot eye, teal inlay ring, original split-bell emblem. Side/front/top and hand scale. Must fit tower socket; portable with both hands.')]:add('14_Items','ITEM',sub,title,assets,desc+' Clean cream modeling reference sheet, plausible crafted construction.')
add('14_Items','FP','ROD_HELD','First-person rod presentation','SK_BH_PlayerArms,SM_BH_BasicRod','Player eye168cm. Both believable gloved hands, fingerless brown leather, cream sleeves; basic oak rod and brass reel held lower right, line guides visible, center view unobstructed. Fishing pond background softly simplified. No UI. Correct hand anatomy.')
add('14_Items','FP','KNIFE_HELD','First-person knife presentation','SK_BH_PlayerArms,SM_BH_IronKnife','Same hands/gloves/sleeves as rod view.28cm iron knife in right hand low ready pose; open left hand lower-left. Three small grip/attack follow-through details. Center view unobstructed, village backdrop, no gore/no UI.')
for sub,desc in [('WOOD','crate, barrel, bucket, bench, table, carved sign, two-rail fence section, dock post'),('FISHING','net, coiled rope, hook, cork float, bait jar, fish rack, rod stand, fish basket'),('FORGE','anvil, hand-cranked grindstone, hammer, tongs, wall tool rack'),('VILLAGE','warm lantern, teal split-bell banner, flower pot, striped teal/cream market awning, notice board, small bronze bell ornament')]:add('15_Props','PROPSET',sub,sub.title()+' prop family','SM_BH_Props_'+sub,'Labeled reusable prop family sheet: '+desc+'. Same honey oak/dark timber/pale stone/bronze/teal materials, generous spacing, separate 3/4 objects and a 1m scale ruler, no random extra props.')
add('00_Style','MATERIAL','BIBLE','Material and surface swatches','M_BH_Master','Fourteen labeled samples: honey oak, dark timber, pale limestone, weathered limestone, bronze, iron, rope, teal fabric, cream cloth, leather, meadow grass, cream flowers, turquoise water, teal roof shingles. Stylized crafted believable surfaces, broad detail not noisy grime. Palette from bible, daylight-neutral presentation.')
for sub,desc in [('DAY_MASTER','Full island late-morning sunlight study matching master aerial camera and layout, warm southwest sun, cool fill, clouds and turquoise pond.'),('SHOP_INTERIOR','Inside Bram forge toward south counter and sunlit village; warm lantern bounce, readable dark timber and tools, no night lighting.'),('BELLTOWER','Same tower viewed up northern path; pale stone remains detailed in warm sun, blue sky, soft shadows, bronze bell clear.')]:add('17_Lighting','LIGHTING',sub,'Lighting '+sub.lower().replace('_',' '),'L_Bellheart',desc+' Small exposure/color swatches optional, no sunset, no bloom haze obscuring structure.')
for sub,desc in [('HUD_MASTER','Full original HUD over pond eye-level view: lower-left heart100/100, lower-center four small slots rod/knife/line/basket, upper-right crown32, quest below THE MISSING BELLHEART / Speak to Orin, tiny crosshair and E Interact, small Cloudfin landed notice.'),('SHOP_DIALOGUE','Two clearly separated UI studies over muted world: SHOP small teal card IRON KNIFE / Damage8 to18 /24 crowns /E Buy; DIALOGUE lower narrow panel MIRA / The pond is restless today. / Tell me about fishing. / Show me your supplies. Readable cream typography and restrained bronze corners.'),('FISHING_QUEST','Two clearly separated original UI studies: compact fishing tension arc and HOLD TO REEL with release hint; quest update panel THE MISSING BELLHEART / Bring the bronze fragment to Orin with three small checklist rows. No giant menus.')]:add('16_UI','UI',sub,'UI '+sub.lower().replace('_',' '),'WBP_BH_'+sub,desc+' Fantasy crafted but highly legible UI, dark teal backing, original simple crown and split-bell icon. Do not trace supplied HUD.')
for sub,desc in [('ARRIVAL_FISHING_MIRA','Three wide cinematic gameplay panels: first-person arrival at south dock looking north; fishing central pond from south bank toward village; talking to Mira at western fishing-shop counter. Same island and Mira.'),('FORGE_PATH_BOSS','Three wide gameplay panels: shopping at Bram forge, walking north from plaza toward same bell tower, Bellcrab emerging onto eastern pond bank. Same Bram and boss references.'),('COMBAT_INSTALL_FINALE','Three wide gameplay panels: first-person knife against telegraphing Bellcrab on eastern arena; carrying/installing70cm Bellheart at tower service-deck socket; bronze bell ringing with clearing cloud band and restored village below. Late morning throughout.')]:add('01_Island','GAMEPLAY',sub,'Gameplay moments '+sub.lower().replace('_',' '),'L_Bellheart',desc+' Actual playable first-person framing with restrained minimal HUD, gloves consistent. These are concept targets not screenshots.')
def save():
    old={e['id']:e for e in json.loads((BASE/'reference_manifest.json').read_text()).get('references',[])} if (BASE/'reference_manifest.json').exists() else {}
    for e in entries:
        if e['id'] in old:e.update({k:v for k,v in old[e['id']].items() if k in ['status','provenance','review_notes','sha256','source_path','dependencies']})
    (BASE/'reference_manifest.json').write_text(json.dumps({'schema_version':1,'phase':'0','complete':False,'style_bible':'BELLHEART_STYLE_BIBLE.md','references':entries},indent=2),encoding='utf-8')
    print(len(entries),'planned sheets')
if __name__=='__main__':save()
