import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const browser=await chromium.connectOverCDP(process.env.CLOUDWAKE_CDP||'http://127.0.0.1:55041');
const page=await browser.contexts()[0].newPage();
await page.setViewportSize({width:1440,height:900});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:4173');
await page.evaluate(()=>{localStorage.removeItem('cloudwake-save-v1');localStorage.removeItem('cloudwake-layout-v1');});
await page.reload();await page.waitForFunction(()=>window.cloudwake?.getSnapshot().artistModelLoaded===true);
await page.screenshot({path:'art/title-screen.png'});await page.locator('#start').click();
await page.locator('#settingsBtn').click();await page.keyboard.press('Tab');
assert.equal(await page.locator('#modal').isVisible(),false);assert.equal(await page.locator('#editor').isVisible(),true);
const layout=await page.evaluate(()=>window.cloudwake.getLayout());const tree=layout.objects.find(o=>o.name==='Lantern_Tree');tree.position[0]+=1;
await page.locator('#importLayout').setInputFiles({name:'layout.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(layout))});
assert.equal((await page.evaluate(()=>window.cloudwake.getLayout())).objects.find(o=>o.name==='Lantern_Tree').position[0],tree.position[0]);
await page.locator('#saveLayout').click();
const downloadPromise=page.waitForEvent('download');await page.locator('#exportLayout').click();const download=await downloadPromise;assert.equal(download.suggestedFilename(),'cloudwake-layout.json');
await page.locator('#objectSelect').selectOption('Lantern_Tree');await page.screenshot({path:'art/workshop.png'});
await page.locator('#closeEditor').click();await page.waitForTimeout(1300);await page.screenshot({path:'art/harbor-gameplay.png'});
assert.deepEqual(errors,[]);await page.evaluate(()=>localStorage.removeItem('cloudwake-layout-v1'));await page.reload();
await fs.writeFile('art/final-smoke.json',JSON.stringify({passed:true,errors,checks:['Blender model loaded','menu to workshop keyboard transition','layout JSON import changes transform','layout save','layout download','gameplay render']},null,2));
console.log('PASS: Blender model, menu/editor transitions, layout import/export and render');await page.close();await browser.close();
